---
- name: Update and upgrade packages
  hosts: 127.0.0.1
  become: true
  tasks:
    - name: Run apt update
      apt:
        update_cache: true
    - name: Run apt upgrade
      apt:
        upgrade: true
# Make sure some things are installed
# Update apt cache again and install
    - name: Install base packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: ['curl', 'logwatch', 'whois', 'htop', 'btop']
