#Ansible playbook to install some stuff, upgrade stuff
#Not enabling dist-upgrades because i don't want to possibly hose a remote system 
---
- hosts: all
  become: true

  tasks:
     - name: Update system
      apt:
        update_cache: yes # apt-get update
        upgrade: full

    #- name: "Update dist"
    #  apt:
    #     upgrade: dist

    - name: Update
      shell: apt-get update -y
    - name: Upgrade
      shell: apt-get upgrade -y
    #- name: DistUpgrade
    #  shell: sudo apt-get dist-upgrade -y
    - name: Run autoremove
      shell: apt-get autoremove -y
    - name: Install prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
      tags: [ system ]

    - name: Install base packages
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'curl', 'logwatch', 'whois', 'htop','btop' ]
      tags: [ system ]
